knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: knp_sort           # sort field query parameter name
        sort_direction_name: knp_dir  # sort direction query parameter name
        distinct: true                  # ensure distinct results
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/bootstrap_v5_fa_sortable_link.html.twig'
        filtration: '@KnpPaginator/Pagination/bootstrap_v5_filtration.html.twig'
