vich_uploader:
    db_driver: orm

    mappings:
        formation_images:
            uri_prefix: /uploads/formations
            upload_destination: '%kernel.project_dir%/public/uploads/formations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        lesson_videos:
            uri_prefix: /uploads/lessons/videos
            upload_destination: '%kernel.project_dir%/public/uploads/lessons/videos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer