parameters:
    youtube_api_key: '%env(YOUTUBE_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\YouTubeSearchService:
        arguments:
            $apiKey: '%youtube_api_key%'