# This file is the entry point to configure your own services.

parameters:
    investment_images_directory: '%kernel.project_dir%/public/uploads/investments'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # 🔥 CONFIG IMAGE UPLOADER
    App\Service\InvestmentImageUploader:
        arguments:
            $targetDirectory: '%investment_images_directory%'